plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android" version "1.9.24"
}

android {
    namespace "com.jhonaiquel.better_screenshot_prevention"   // ← THIS IS THE IMPORTANT LINE
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        minSdk 21   // you can keep 16 if you really need it, but 21 is safer now
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24"
}
